### ISSUE TITLE
Version "mock" des différents endpoints du parcours lycéen

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#163]
Créer des endpoints de type mock/bouchons afin que les contrats d'interfaces apparaissent dans le Swagger.
De cette manière Maxime peut connecter le front de manière asynchrone en juillet / août.

- [ ] récupération profil #165 --> renvoie un résultat au hasard entre deux profils fixe, un qui n'a ni domaines pro ni mots clés et l'autre qui est complet
- [ ] édition profil #141 --> aucun effet de bord 
- [ ] recherche formation #164 et métiers #174 --> toujours le même tableau de résultat, soit formations soit métiers
- [ ] suggestions sans pagination #143 --> toujours le même tableau de résultat

**Comment by Maxgux** [comment]
@aureliadelzottoOCTO Pour la récupération et modif du profil élève supprimer id

**Comment by Maxgux** [comment]
@aureliadelzottoOCTO renvoyer un code 204 pour la modif du profil
