### ISSUE TITLE
remonter etl et suggestions à la racine du dépôt

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#176]
mettre etl et suggestions à la racine
```[tasklist]
### Tasks
- [ ] séparer etl et suggestions en deux projets springboot indépendants
- [ ] charger les données utilisées pour les suggestions personnalisées depuis la bdd postgre
- [ ] créer dans la bdd postgre les tables nécessaires aux suggestions et ml
- [ ] alimenter les données suggestiosn et ml depuis postgre
```
