### ISSUE TITLE
en tant que lycéen, je peux lier mon compte MPS à mon compte "carte parcoursup" et retrouver mes favoris parcoursup dans MPS

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#227]
Point d'accès à la fonction depuis tableau de bord:
https://www.figma.com/design/oXT35cxqKWY168pQBVgixB/MonProjetSup?node-id=158-21293&t=SVh0clVyZBTzCcQm-4

Ecran de consentement:
https://www.figma.com/design/oXT35cxqKWY168pQBVgixB/MonProjetSup?node-id=4328-164046&t=SVh0clVyZBTzCcQm-4

## Contexte
_En tant que lycéen, 
je veux lier mon compte MPS (MonProjetSup) à mon compte PS (ParcoursSup)
afin de synchroniser mes formations favorites PS et MPS_

### **Côté front** 
- Le front redirige vers l'OpenID PS et récupère un JWT qu'il envoie au back

### **Côté back** 
- Lors de la réception du token, le back vérifie sa validité et si valide, extrait l'id PS du JWT et le stock en base MPS dans le profil de l'élève avec une date de stockage pour revérification tous les ans. 
- Lors de l'appel au profil, le back appelle l'API ParcoursSup afin de vérifier si de nouveaux triplets d'affectation ont été ajoutés en favoris. Si c'est le cas, il les stocke en BDD et renvoie le profil. Si un des triplets d'affectation n'existe pas, on l'ignore.

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/monprojetsup/issues/292
- [ ] https://github.com/betagouv/monprojetsup/issues/293
```

**Comment by Numero7** [comment]
- [ ] récupérer favoris back to back d'une id de la bdd (en dur pour les test)
- [ ] ajouter un endpoint de liaison d'un compte mps à un compte psup qui mange un jwt (ou éventuellement un code d'accès)

Pour les tests, crer une id lycéen psup via https://dossier.parcoursup.fr/Candidat/carte


Authentification back à back se base sur le well kwown 
    https://authentification.parcoursup.fr/Authentification/.well-known/openid-configuration
normalement il y a juste besoin de mettre une ligne dans le properties
    https://authentification.parcoursup.fr/Authentification/

https://authentification.parcoursup.fr/Authentification/oauth2/token 
avec login "mpsApi" et le mdp passé en PM



API favoris parcoursup disponible pour tests

https://ws.parcoursup.fr/ApiFavoris/favoris/*numéroUtilisateur*
https://ws.parcoursup.fr/ApiFavoris/public/swagger-ui/index.html#/

L'API mange un id parcoursup et renvoie une liste:
[tacod, note, commentaire]
Dans un premier temps on oublie les notes et commentaires.
pour chaque tacod, il y adeux cas:
* soit le tacod est déjà dans les favoris MPS --> on fait rien
* soit pas encore et le tacod existe --> on ajoute le tacod, 
* soit pas encore et le tacod existe pas --> on ne fait rien

Remarque: correspondance univoque de tacod vers mpscod

id parcoursup de la carte https://dossierappel.parcoursup.fr/Candidat/carte
(différent du dossier candidat)

*********************

lier les comptes MPS et psup

côté front: maxime redirgie vers l'openid pasup et récupère un token (si ça se passe bien) qu'il repasse au back
côté back: du token est extarite l'id parcoursup, stockée en base MPS + date pour revérification tous les ans

***********************

appel à L'API:
le principe posé avec Vincent c'est que c'est du back à back. 
Soit sur un utilisateur soit sur plusieurs tous les connectés  (API dédiée pilotée par Vincent).
Rafraîchîssement à 1Hz pour ne pas créer d'incompréhension si un utilisateur ouvre en même temps MPS et la caret de parcoursup

intelrocuteur côté psup vincent

Authentification  en demandant un token via

https://authentification.parcoursup.fr/Authentification/oauth2/token

client id et token sur demande

**Comment by Numero7** [comment]
@Maxgux 

Point d'accès à la fonction depuis tableau de bord:
https://www.figma.com/design/oXT35cxqKWY168pQBVgixB/MonProjetSup?node-id=158-21293&t=SVh0clVyZBTzCcQm-4

Ecran de consentement:
https://www.figma.com/design/oXT35cxqKWY168pQBVgixB/MonProjetSup?node-id=4328-164046&t=SVh0clVyZBTzCcQm-4

As-tu besoin d'autres éléments graphiques pour lier les deux comptes?

**Comment by Maxgux** [comment]
Il manque un écran pour supprimer le consentement non @Numero7  ?

**Comment by Numero7** [comment]
Non pas la peine, ils envoient un email au support si ils veulent supprimer le consentement. Par contre on peut ajouter une phrase dans l'écran de consenetement "ajouter "Cette autorisation est valable toute la durée de l'année scolaire en cours, et révocable en écrivant à support@monprojetsup.fr.""

**Comment by Numero7** [comment]
Si on est submergé de demandes (ce dont je doute fort) on ajoutera la fonction de révocabilité en ligne....

**Comment by Maxgux** [comment]
En attente de PS pour les CORS, ne pas nous rediriger automatiquement vers https, nous donner accès sur un env de test

**Comment by Maxgux** [comment]
Ok de notre côté pas de MEP de la part d'onisep prévue avant le 12 novembre donc pour le moment la feature est masqué côté front il faut les deux variables d'env VITE_PARCOURSUP_OAUTH2_URL et VITE_PARCOURSUP_OAUTH2_CLIENT pour l'activer

**Comment by Numero7** [comment]
MEP = "mise en production" ?

**Comment by Numero7** [comment]
pour l'instant quand je clique sur le carré "associer mon compte Parcoursup", je termine sur la carte et le compte ne semble pas associé

**Comment by Maxgux** [comment]
@Numero7 c'est bon normalement

**Comment by Numero7** [comment]
@aureliadelzottoOCTO 


Je viens de retester tout le parcours lycéen.

sur uat
https://app.mps.uat.avenirs.onisep.fr/
pour le compte 
 elevetest25.2DE.LGT2.onisep
onisep$eleve2024

* Associer les deux comptes
—> ok. Dans la BDD MPS sur uat je vois bien la ligne


L’association des comptes semble bien foncitonner.
Par contre, je ne récupère pas les favoris pour l'instant.

id_parcoursup date_mise_a_jour id_eleve
1396601 2024-11-21 f:7aa21b24-1feb-483b-9090-a83a15cc6c9e:78d8d91e-6384-4665-ade5-d2e75479f6f2

Pour info le compte associé est 
hugo.gimbert@gmail.com 
mot de passe
dyzgi6-gitfyC-cofta!


* Récupérer les favoris
—> j’ajoiute « MPSI » en favori côté MPS

![Image](https://github.com/user-attachments/assets/684d315f-08e7-4892-985b-bc0be2575781)


—> j’ai des favoris de ce type côté Psup,
notamment g_ta_cod=4271

![Image](https://github.com/user-attachments/assets/664e2d06-2e81-4f5c-9172-68c8c8a88c72)


Mais rien ne remonte côté MPS, même après connection / déconnexion

![Image](https://github.com/user-attachments/assets/d834f408-1865-4ec6-bebf-738e84887e71)

**Comment by Numero7** [comment]
@Maxgux @aureliadelzottoOCTO proposition de  fonctionnement pour gèrer le cas où le compte est associé dans la bd MPS mais parcoursup renvoie une 403. Cas rencontré par Aurélia aujourd'hui. 

Proposition de fonctionnement:
Au cas où parcoursup renvoie une 403 au moment de récupérer les favoris,
Le back en retour d'appel à profil, inclut un booléen qui prévient le front qui ouvre un popup, 

"Veux-tu continuer à synchroniser tes favoris MPS et tes favoris Parcoursup? Oui / Non / Décider plus tard"

On ouvre le popup au plus une fois par session. 

Si la réponse est non on efface la ligne de correspondance des deux comptes de la bdd. 
Si la réponse est oui on conserve la ligne et on enchaine sur le process d association. 
Si la réponse est plus tard on attend la prochaine session pour redemander 

Je le mets dans un coin du backlog

**Comment by Numero7** [comment]
@aureliadelzottoOCTO @Maxgux ça fonctionne, bien joué!
