### ISSUE TITLE
créer davantage de tests API suggestions

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#285]
```[tasklist]
### Tasks
- [x] exploiter automatiquement les profils de référence
- [ ] https://github.com/betagouv/monprojetsup/issues/297
- [ ] https://github.com/betagouv/monprojetsup/issues/298
```

**Comment by Numero7** [comment]
* exploiter automatiquement les profils de référence
* vérifier le bon décodage du type de bac
* vérifier une par une que chaque type d'explication est bien remonté
