### ISSUE TITLE
retours sur parcours inscription et tableau bord

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#47]
Tickets centralisant les retours sur le tunnel inscription / tableau de bord.

- [x] Sur la recherche "pass", le lycéen s'attend très probablement à avoir "L1 - PArcours spécifique Santé (PASS)" qui ressort en premier. ce serait bien de prioriser le match exact devant les matches préfixes et les matches exacts et préfixes devant les matches avec correction ortho. Egalement en cas de match exact ou préfixe, pas clair que ce soit nécessaire d'ajouter les matches avec correction orthographique (à discuter).

![image](https://github.com/betagouv/monprojetsup/assets/1570019/8c5f28ff-46bf-408c-a068-34c5b2dd42ca)

```[tasklist]
### Tasks
- [x] bouton riche colonnes  -> ligne en responsive
- [x] Retours wording
- [x] dans le tableau de bord, masquer le bloc "consulte les formations post-bac que tu as sélectionnées" quand la sélection est vide
- [x] dans le tableau de bord, dans le bloc explorer, arrêter la phrase avant "et découvres-en"
- [ ] dans le parcours d'inscirption, depuis l'écran "spécialités" après avoir choisi des spécialités, en cliquant sur continuer -->  retour --> continuer --> retour les spécialités disparaissent
- [x] dans le parcours d'inscription, écran villes, trois occurences de "Saint-Nazaire" sans possibilité de les distinguer
- [x] dans le parcours d'inscirption, écran "formations post-bac identifiées" "PASS" ne ressort pas en premier sur la recherche pass
- [x] une fois effectué le parcours d'inscription, le bouton de naviogation "accueil" n'emmène pas au tableau de bord mais à un écran vide
- [x] Dans Etudes supérieures, aucun champs n'est obligatoire
- [x] Alerte succès et erreur dans modification profil peuvent s'afficher en double
```

**Comment by Numero7** [comment]
@Maxgux j'ai testé aussi exhaustivement que possible, globalement c'est nickel, à part quelques détails. J'ai créé une "task" dans la "tasklist" pour chaque remarque. C'est bon pour toi comme manière de procéder?

**Comment by Numero7** [comment]
@Maxgux pour plus de visibilité sur la colonne "feddback PO", je te propose de bouger ce ticket dans "todo", qu'en dis-tu?

**Comment by Maxgux** [comment]
@Numero7 On reparle de ce ticket demain

**Comment by Numero7** [comment]
top pour saint-nazaire :-) 

![Image](https://github.com/user-attachments/assets/f630fb3a-bf2a-403e-bbf2-2267e5b3ea1d)
