### ISSUE TITLE
petites évolutions API explanations

### ISSUE THREAD

**Issue by Numero7** [betagouv/monprojetsup#76]
```[tasklist]
### Tasks
- [x] supprimer explication « bac »
- [x] specialites explnaation en list et int au lieu de double
- [x] virer search
- [x] decimer interests
- [x] ajouter un profile de référence illustrant l'utilisation de chaqcun des paramètres
```

**Comment by Numero7** [comment]
@aureliadelzottoOCTO j'ai maj l'API suggestions, ça devrait renvoyer tous les types d'explications normalement. Voilà un profil avec lequel c'est le cas 

"pf": {
      "login": "demo_anne_sophie",
      "nom": "G",
      "prenom": "Hugo",
      "niveau": "term",
      "ine": "xxx",
      "bac": "Générale",
      "duree": "long",
      "apprentissage": "C",
      "geo_pref": [],
      "spe_classes": [
        "Physique-Chimie (PC)",
        "Mathématiques"
      ],
      "retours": [
        {
          "author": "demo_prof",
          "type": "opinion",
          "key": "fl2009",
          "content": "ok",
          "date": "2024-05-08"
        },
        {
          "author": "demo_prof",
          "type": "opinion",
          "key": "fr90",
          "content": "discuss",
          "date": "2024-05-08"
        },
        {
          "author": "demo_prof",
          "type": "comment",
          "key": "fr90",
          "content": "ouaip...",
          "date": "2024-05-08"
        },
        {
          "author": "demo_prof",
          "type": "comment",
          "key": "fl2009",
          "content": "génial!!",
          "date": "2024-05-08"
        },
        {
          "author": "demo_anne_sophie",
          "type": "favori",
          "key": "fl54",
          "content": "mls;sms",
          "date": "2024-05-26"
        },
        {
          "author": "demo_anne_sophie",
          "type": "favori",
          "key": "fr90",
          "content": "a",
          "date": "2024-05-26"
        },
        {
          "author": "demo_anne_sophie",
          "type": "favori",
          "key": "fl34",
          "content": "sss",
          "date": "2024-05-26"
        },
        {
          "author": "demo_anne_sophie",
          "type": "favori",
          "key": "fl32",
          "content": "B/L kezako?",
          "date": "2024-05-26"
        },
        {
          "author": "demo_anne_sophie",
          "type": "favori",
          "key": "fl680002",
          "content": "bof",
          "date": "2024-05-28"
        },
        {
          "author": "demo_anne_sophie",
          "type": "favori",
          "key": "fl51",
          "content": "",
          "date": "2024-06-05"
        },
        {
          "author": "demo_anne_sophie",
          "type": "favori",
          "key": "fl13",
          "content": "",
          "date": "2024-06-05"
        },
        {
          "author": "demo_anne_sophie",
          "type": "favori",
          "key": "fl210",
          "content": "",
          "date": "2024-06-05"
        }
      ],
      "scores": {
        "T_ITM_566": 1,
        "T_ITM_PERSO8": 1,
        "T_IDEO2_4811": 1
      },
      "moygen": "16",
      "msgs": {},
      "choices": {
        "MET_171": {
          "fl": "MET_171",
          "status": 0
        },
        "MET_570": {
          "fl": "MET_570",
          "status": 0
        },
        "SEC_4835": {
          "fl": "SEC_4835",
          "status": 0
        },
        "fl210": {
          "fl": "fl210",
          "status": 1,
          "score": 3
        },
        "MET_450": {
          "fl": "MET_450",
          "status": 0
        },
        "MET_211": {
          "fl": "MET_211",
          "status": 0
        },
        "fl33": {
          "fl": "fl33",
          "status": 0
        },
        "fl850010": {
          "fl": "fl850010",
          "status": 0
        },
        "fl840009": {
          "fl": "fl840009",
          "status": 0
        },
        "MET_936": {
          "fl": "MET_936",
          "status": 0
        },
        "fl2047": {
          "fl": "fl2047",
          "status": 0
        },
        "MET_737": {
          "fl": "MET_737",
          "status": 0
        },
        "fl1002023": {
          "fl": "fl1002023",
          "status": 0
        },
        "fl2089": {
          "fl": "fl2089",
          "status": 0
        },
        "fl691103": {
          "fl": "fl691103",
          "status": 0
        },
        "fl691027": {
          "fl": "fl691027",
          "status": 0
        },
        "fl840001": {
          "fl": "fl840001",
          "status": 0
        },
        "MET_773": {
          "fl": "MET_773",
          "status": 0
        },
        "fl2009": {
          "fl": "fl2009",
          "status": 0
        },
        "MET_536": {
          "fl": "MET_536",
          "status": 0
        },
        "fl1831": {
          "fl": "fl1831",
          "status": 0
        },
        "fl840003": {
          "fl": "fl840003",
          "status": 0
        },
        "fl691064": {
          "fl": "fl691064",
          "status": 0
        },
        "MET_537": {
          "fl": "MET_537",
          "status": 0
        },
        "SEC_4865": {
          "fl": "SEC_4865",
          "status": 0
        },
        "SEC_5712": {
          "fl": "SEC_5712",
          "status": 0
        },
        "fl691132": {
          "fl": "fl691132",
          "status": 0
        },
        "fl691056": {
          "fl": "fl691056",
          "status": 0
        },
        "fl2013": {
          "fl": "fl2013",
          "status": 0
        },
        "MET_707": {
          "fl": "MET_707",
          "status": 0
        },
        "fl691134": {
          "fl": "fl691134",
          "status": 0
        },
        "fl691057": {
          "fl": "fl691057",
          "status": 0
        },
        "MET_589": {
          "fl": "MET_589",
          "status": 0
        },
        "fl2018": {
          "fl": "fl2018",
          "status": 0
        },
        "fl691052": {
          "fl": "fl691052",
          "status": 0
        },
        "SEC_4859": {
          "fl": "SEC_4859",
          "status": 0
        },
        "fl17": {
          "fl": "fl17",
          "status": 0
        },
        "fl16": {
          "fl": "fl16",
          "status": 0
        },
        "fl13": {
          "fl": "fl13",
          "status": 1,
          "score": 3
        },
        "fl11": {
          "fl": "fl11",
          "status": 0
        },
        "fl51": {
          "fl": "fl51",
          "status": 1,
          "score": 3
        },
        "fl2023": {
          "fl": "fl2023",
          "status": 0
        },
        "MET_7835": {
          "fl": "MET_7835",
          "status": 0
        },
        "fl2022": {
          "fl": "fl2022",
          "status": 0
        },
        "fl2029": {
          "fl": "fl2029",
          "status": 0
        },
        "fl2028": {
          "fl": "fl2028",
          "status": 0
        },
        "SEC_4846": {
          "fl": "SEC_4846",
          "status": 0
        },
        "fl691118": {
          "fl": "fl691118",
          "status": 0
        },
        "fl691033": {
          "fl": "fl691033",
          "status": 0
        },
        "MET_885": {
          "fl": "MET_885",
          "status": 0
        },
        "fl691074": {
          "fl": "fl691074",
          "status": 0
        },
        "fl691153": {
          "fl": "fl691153",
          "status": 0
        }
      }
    },
